### ISSUE TITLE
Add variants to LoqusDB

### ISSUE THREAD

**Issue by pbiology** [Clinical-Genomics/BALSAMIC#1130]
## Need
To keep track of local variants we should add the variants we find to LoqusDB. This needs to be done for both normal and tumor samples.

## Suggested approach
*A few sentences about the intended solution* 

## Considered alternatives
*Were there alternative approaches which have been rejected?*

## Can be closed when
- [ ] loqusdb tumor SNV Frequencies for WGS
- [ ]  loqusdb tumor SV Frequencies for WGS
- [ ]  loqusdb somatic SNV Frequencies for WGS
- [ ]  loqusdb somatic SV Frequencies for WGS
- [ ] Updated documentation

## Blockers
*Anything preventing this from happening?*

**Comment by ivadym** [comment]
What has been done so far: https://github.com/Clinical-Genomics/cg/issues/1559

Somatic variants uploaded:
- SNV (`vcf-snv` tag): `tnscope.vcf.gz` file
- SV (`vcf-sv` tag): `svdb.vcf.gz` file

Tumor variants uploaded:
- SNV (`vcf-snv-germline-tumor` tag): `tumor.dnascope.vcf.gz` file
- SV: None

**Comment by pbiology** [comment]
How is this connected to #1181 ? This issue needs refinement

**Comment by khurrammaqbool** [comment]
As I understand, It was completed in https://github.com/Clinical-Genomics/cg/issues/2211

**Comment by khurrammaqbool** [comment]
Upon closer look, I realise that I misunderstood this as a redundant issue. 
Is it opened with intention to create separate databases for unfiltered somatic and germline variants?

**Comment by khurrammaqbool** [comment]
If it is then the title should be updated to avoid confusion.

**Comment by ivadym** [comment]
If that's the case, it should be considered a new issue. I'm closing this one because variants are being uploaded to Loqusdb since the CG issue was merged.

Somatic variants uploaded (`loqusdb-somatic`):
- `SNV` (`vcf-snv-clinical` tag): `.tnscope.clinical.filtered.pass.vcf.gz` file
- `SV` (`vcf-sv-clinical` tag): `.svdb.clinical.filtered.pass.vcf.gz` file

Tumor variants uploaded (loqusdb-tumor):
- SNV (`vcf-snv-germline-tumor` tag): `tumor.dnascope.vcf.gz` file (from WGS tumor-only and tumor-normal cases)
- SV: (`vcf-sv-germline-tumor` tag): `tumor.manta_germline.vcf.gz` file (from only WGS tumor-normal cases)
