### ISSUE TITLE
[Assessment] Reanalysis (new downsampling) in BALSAMIC where a variant is missed by VarDict

### ISSUE THREAD

**Issue by moahaegglund** [Clinical-Genomics/BALSAMIC#1396]
### Description

This is about an analysis of a Horizon Discovery reference sample, HD803.

The sample was downsampled and analysed for the first time during 2022 and analysed with BALSAMIC version 8.2.10. The sample was downsampled again to the same amount of reads and reanalysed in version 13.0.0 (and 13.0.1) of BALSAMIC.
One of the listed variants, NRAS:p.Q61K, with an expected allele frequency of 12.5% is picked up by VarDict in the first analysis (BALSAMIC v. 8.2.10) but missed in the second (BALSAMIC v. 13). The variant is clearly visible in IGVviewer in the second analysis and it's also picked up by DNAscope.

### Suggested approach

Would be interesting if you could look into this, more information to identify the sample is available[ here](https://docs.google.com/spreadsheets/d/12lKCdpH58dLLt2EPBMS-flE3prnjmJKWR-wxInk3zz4/edit#gid=0).

**Comment by mathiasbio** [comment]
I completely forgot about this, I'm looking into it now!

**Comment by mathiasbio** [comment]
I have tried re-running VarDict specifically on the bamfile to try to isolate the issue, and I had a lot of issues making it work outside of balsamic. But I managed to at least make it run using standard VarDict, not the VarDict-java that we're using in the snakemake rule. However the downstream filtering using  `teststrandbias.R` failed with errors:

```
Error in fisher.test(matrix(c(d[i, 10], d[i, 11], d[i, 12], d[i, 13]),  : 
  all entries of 'x' must be nonnegative and finite
Execution halted
```
But I output the intermediate results from VarDict and could at least find the variant there.
`
strikingbeagle	1	1	115256530	115256530	G	T	335	39	65	231	6	33	G/T	0.1164	2;2	43.1	1	35.7	1	60.0	38.000	0.1141	0.0060	0	1.000	1	1.0	38	333	CATGGCACTGTACTCTTCTT	TCCAGCTGTATCCAGTATGT	1:115256320-115256699	SNV	0.667	0`

But I don't know if the issue lies with VarDict-java or with the downstream filtering. Maybe we can check and see if we have updated VarDict between this and the previous version... 🤔

**Comment by mathiasbio** [comment]
So with some help from @khurrammaqbool (❤️ ) I managed to get vardict-java to work as well, and when I ran that output through the teststrandbias.R it doesn't fail, so it seems indeed like there are some compatibility issues between VarDict and the java-version of VarDict with this R script. However, regardless! Whereas I could find the variant in the regular VarDict it is gone in the java-version...despite being run with the exact same commands.

**Comment by mathiasbio** [comment]
Looks like the outputs for the java-version of VarDict and the version without java is very different:

Number of variants in the non-java version: 3145
Number of variants for the java version: 10593

In the dockerfile for VarDict we are installing these two callers:
  - vardict=2019.06.04
  - vardict-java=1.8.3

And it seems that they correspond to different versions of vardict, where 2019.06.04 corresponds to VarDict 1.6.0.

Maybe the reason why it was called before and not now is that we were using a different version...

**Comment by mathiasbio** [comment]
Looks like we were using VarDict-java back in the v8.2.10 times however: 
https://github.com/Clinical-Genomics/BALSAMIC/blame/v8.2.10/BALSAMIC/snakemake_rules/variant_calling/somatic_tumor_only.rule

But it looks like we were using a different version of vardict-java: https://github.com/Clinical-Genomics/BALSAMIC/blob/v8.2.10/BALSAMIC/containers/varcall_py36/varcall_py36.yaml

**bioconda::vardict-java=1.7**

I'll restart VarDict now with the old container and see if the old version will call the variant.

**Comment by mathiasbio** [comment]
Unfortunately it didn't change anything, running vardict-java 1.7 with the old container produced the exact same number of variants: 10593 and I cannot find the variant there either. 

It also doesn't seem like any of the settings have changed for this rule since then. So conclusion: **I'm still confused**

**Comment by mathiasbio** [comment]
Okay, it seems like we finally have some clarity on this issue. So! To begin, thanks to @khurrammaqbool for helping me look into this. 

Running the vardict command with the "-p" flag forced VarDict to report some stats on the variant which helped us identify the issue. So unlike the other variants VarDict set these values for the "Bias" parameter: 2;1 which means that VarDict determined that the reference allele has no strand bias (code 2), whereas the alt-allele has strand bias (code 1) (https://github.com/AstraZeneca-NGS/VarDictJava). 

I don't know where VarDict sets it's threshold but it seems that in the original downsampled case there were 7 forward reads and 114 reverse reads for the variant whereas in the re-downsampling we received instead 8 forward vs 196 reverse reads. Which put the fraction of forward vs reverse at 0.04, which is lower than in the previous run which was 0.06. And it's possible that the threshold for VarDict is at 0.05 based on the correlation between the stats and these strandbias parameters.

So in short, in this case, the randomness of the downsampling meant that this variant just got into the territory where it would be filtered out by VarDict (unless it also had an AF above 20%, see qoute from VarDictJava github below)

> Variant has not "2;1" bias or variant frequency more than 20%. If both conditions aren't met, then variant mustn't be SNV and any of variants refallele or varallele lengths must be more than 3 nucleotides.

But...this isn't all. It seemed strange that there should be such a strand-bias for a true variant, and when looking at other variants called in the region it was clear that nearly all of them where underrepresented as "forward reads".

| RefFwdReads | RefRevReads | AltFwdReads | AltRevReads |
|-------------|-------------|-------------|-------------|
|          72 |         908 |           0 |           0 |
|          75 |         896 |           0 |           0 |
|          69 |         928 |           0 |           0 |
|          69 |         928 |           1 |           0 |
|          73 |         914 |           0 |           1 |
|          71 |         951 |           0 |           0 |
|          70 |         932 |           0 |           3 |
|          76 |         991 |           0 |           0 |
|          73 |         977 |           0 |           1 |
|          76 |        1006 |           0 |           1 |
|          75 |        1002 |           0 |           0 |
|          73 |        1023 |           0 |           0 |
|          76 |        1021 |           0 |           0 |
|          66 |         920 |           6 |         119 |

And it made me suspicious of how VarDict determines strandbias, so I simply looked in IGV at the reads for the variant of interest and counted the F1R2 and F2R1 reads in support of the variant, and while I did not count all of them, the sampling alone (25 read-pairs, 9 of which were F2R1, 16 F1R2) strongly suggested that these values from VarDict are not representing F1R2 and F2R1 read-pairs, but something else.

In this issue in VarDict: https://github.com/AstraZeneca-NGS/VarDictJava/issues/239

Someone reports an issue that looks very much like the table above, saying that when R1 and R2 mates overlap the mutation will be judged as being predominantly in the reverse strand and report strand bias. 

Reading through this issue it seems that the default behaviour of VarDict is to count overlapping reads in a read-pair twice, and then if the mutation exists in a read-pair with overlapping mates it will add 1 to fwd and 1 to rev-reads, and that there are optional arguments to make it count the reads only 1 time "-u" and "-UN". 

And it seems that this is the underlying issue in our case...because we're on default using "-u" flag. When I remove this flag and rerun VarDict we get a much more even forward and reverse read count:

| RefFwdReads | RefRevReads | AltFwdReads | AltRevReads |
|-------------|-------------|-------------|-------------|
|         897 |         908 |           0 |           0 |
|         889 |         896 |           0 |           0 |
|         914 |         928 |           0 |           0 |
|         914 |         928 |           1 |           0 |
|         904 |         914 |           0 |           1 |
|         934 |         951 |           0 |           0 |
|         920 |         932 |           0 |           3 |
|         976 |         991 |           0 |           0 |
|         958 |         977 |           0 |           1 |
|         994 |        1006 |           1 |           1 |
|         989 |        1002 |           0 |           0 |
|        1010 |        1023 |           0 |           0 |
|        1007 |        1021 |           0 |           0 |
|         907 |         920 |         115 |         119 |

So it seems if I'm not misunderstanding, that VarDict doesn't actually use the F1R2 strand information but simply counts in how many forward and reverse reads the variant appear, instead of counting the strandedness of the read-pairs. 

But I still can't make sense of these numbers exactly...because I ran the same bamfile through TNscope and there the values are actually reported as ALT_F1R2 and ALT_F2R1, and for this variant these numbers are:

ALT_F1R2 = 139
ALT_F2R1 = 112

Comparing this to the values from VarDict without either "-u" or "-UN" flag:

AltFwdReads = 115
AltRevReads = 119

Doesn't suggest that these are counted twice for overlapping mates as is described in the above issue (Mutation coverage and depth will be calculated twice). Unless a lot of them were also at the same time disregarded for some quality-issue or something...

So I still don't quite understand this, but it seems at least that us using the "-u" flag in VarDict has this problem when the sample has a small insert-size that we may very much over-estimate the strandbias of some variants!!! So two options that I can see..
1. Remove the -u flag and take the extra noise variants that comes from sometimes counting twice...?
2. Replace VarDict with TNscope

**Comment by mathiasbio** [comment]
Closing assessment as a userstory has been made: https://github.com/Clinical-Genomics/BALSAMIC/issues/1396
