### ISSUE TITLE
Ideogram vizualisation in Scout from balsamic data (Myeloid panel)

### ISSUE THREAD

**Issue by genecracker** [Clinical-Genomics/BALSAMIC#564]
Hi,

this is a feature request for the scout visualisation of genetic data from BALSAMIC (Myeloid panel). I just saw a new scout feature for MIP data that allows to visualise chromosome ideograms with coverage plot and SNPs to detec LOH. I think such feature would be a great way to visualise the data from Myeloid panel in relation to CNVs. 

I hope this is the right forum.

Cheers,
Bianca

**Comment by hassanfa** [comment]
Bianca, that's a very good suggestion. I think it is Chromograph that generates these results. We'll look into it.

**Comment by christacosta** [comment]
Hi, 

I found this old issue. We are again and rather urgently interested in being able to detect LOH with BALSAMIC and the myeloid panel. Most urgent is to get it for the TP53-gene (kromosom 17p13.1). But if it is genome-wide that's also great! Could this issue be further investigated? 

Thanks in advance! Christa

**Comment by vwirta** [comment]
Hi Christa,

Copy number calling is something that we will be implementing also for the myeloid panel. 

Regarding your question, would this be for a tumour / normal, or tumour-only analysis?

**Comment by christacosta** [comment]
Hi Valtteri, 

Great! Do you have a rough time estimate for this? Could it be implemented during this year? 

It would be for tumor-only analysis (we don't run paired samples with the myeloid panel and there are no plans to do so). 

I also have another question, would it be possible to get a list with the detected LOH-regions? Alternatively a yes/no output for LOH over the TP53-gene?

**Comment by vwirta** [comment]
For T-only analyses we need a panel of normals to control for normal variation in coverage. We need 30-50 samples unrelated to the disease of question to generate this. Because the number of samples, there is a cost associated with generating this. We can do it once, but for new iterations of the design there must be additional funding to cover this somehow. My understanding is that there is a new design of the myeloid panel being discussed, and I am hesitant to run the panel of normal samples now using the old one.
Can you discuss with Lucia at your end regarding the iteration of the design? She knows more than we do here at our end.

The results can be presented in multiple ways. Let's have a meeting to discuss options when we know the situation with the design.

**Comment by christacosta** [comment]
Ok good to know, we were not aware of the fact that a panel of normals is needed if it's T-only analysis. I will discuss with Lucia regarding the new design of the panel and get back to you. Having a meeting to discuss sounds good!

**Comment by christacosta** [comment]
Hello again, I have discussed with Lucia. We cannot wait until a new design is validated. But we could put together a panel of normals with samples previously analysed with the myeloid panel. We have e.g. CLL-patients where we know from array-CGH that they don't have any copy-number abberations or TP53 mutations. Does this sound good? Scheduling a meeting would be great to discuss details.

**Comment by pbiology** [comment]
Refinement on 2022-12-13:
- No CNV PDF for TGA analysis
- The ideogram could be added to the PDF

**Comment by khurrammaqbool** [comment]
`CNVkit` generates the plots for TN and TO analysis. The next step is to generate the PDF report and upload to Scout. This will be addressed in https://github.com/Clinical-Genomics/BALSAMIC/issues/1140

**Comment by khurrammaqbool** [comment]
The plots are included in the report.
