### ISSUE TITLE
[Failed Analysis]: ImportError: cannot import name 'MetricModel'

### ISSUE THREAD

**Issue by ashwini06** [Clinical-Genomics/BALSAMIC#846]
While testing #845, encountered problems with running rule `collect_custom_qc_metrics` with importing  name 'MetricModel' from 'BALSAMIC.utils.models'

<img width="1428" alt="Screenshot 2022-01-04 at 14 22 41" src="https://user-images.githubusercontent.com/6302819/148065153-81a94306-17d4-4ab7-a14b-0070bf7b1b6f.png">
<img width="1416" alt="Screenshot 2022-01-11 at 09 50 23" src="https://user-images.githubusercontent.com/6302819/148910354-a46308e6-697d-453e-ab41-de4e29ae2e5d.png">

To reproduce:

Test1:

```
source activate D_BALSAMIC_APJ
cd /home/proj/stage/cancer/cases/equalbug
balsamic run analysis -s equalbug.json --run-mode local --snakemake-opt "--cores 8" -r
```

Test2:

```
source activate D_BALSAMIC_APJ
cd /home/proj/long-term-stage/cancer/UMI_analysis_runs_APJ/cancer_test_datasets/panel_TN/stablevaren_testqc
$balsamic run analysis -s stablevaren_testqc.json --snakemake-opt "--until collect_custom_qc_metrics --cores 8" -r --run-mode local
```

**Comment by ivadym** [comment]
Since this rule is now being executed inside the balsamic container, I think its necessary to updated it on stage.

You can pull it from the clinical genomics repository or use my own built: https://hub.docker.com/layers/184200268/ivadym/test/balsamic/images/sha256-a9313518b35f97ee8dbd52cd921810aac6b0ae0c047fe27916e928e8d40e0d44?context=repo

Tell me if the problem persists.

**Comment by ashwini06** [comment]
We do have updated `balsamic.sif` image on stage

<img width="1313" alt="Screenshot 2022-01-11 at 13 05 07" src="https://user-images.githubusercontent.com/6302819/148944850-c060542c-46fe-4721-83a3-ed17b11d8979.png">

**Comment by ashwini06** [comment]
Thanks, now the `collect_custom_qc_metrics` rule works fine 💯
