### ISSUE TITLE
Identify and retrieve metrics of interest for UMI delivery report

### ISSUE THREAD

**Issue by ivadym** [Clinical-Genomics/BALSAMIC#953]
Currently we are not including any UMI Picard metrics in the delivery reports uploaded to Scout for the UMI cases:

- Should we add the UMI specific metrics instead of the Balsamic ones?
- Which metrics should be included in the report?
- Is there any other information that should be taken from BALSAMIC regarding UMIs?

**Comment by ivadym** [comment]
Your insights could be really helpful here @ashwini06.

**Comment by ashwini06** [comment]
@ivadym Indeed it is good to have such metrics for UMI results but currently, very few projects (mostly customer Emma Tham) specifically ordered for UMI workflow results and deeply looked into the generated UMI results. For the rest of the customers between BALSAMIC v7.5 to v9.0, we have generated the UMI results for all panels. But to my knowledge no one has looked into the metrics in detail, to bring some conclusions.

To my knowledge, one crucial metric could be the Median Target coverage value, both from total reads and after UMI collapsing. In order to detect very low AF sensitivities from UMI workflow (AF 0.05%), we need a good target coverage after UMI collapsing (~3000x), In relation to this, the sequencing depth also matters. Also, from Total sequenced reads, it is good to have the duplication rate. 

Related issue: https://github.com/Clinical-Genomics/cgp-cancer-umi/issues/2

Some of these metrics are generated and stored in each analysis case folder `analysis/qc/umi_qc/`
but as mentioned needs more investigation from different projects to define the criteria.

**Comment by ashwini06** [comment]
@ivadym Indeed it is good to have such metrics for UMI results but currently, very few projects (mostly customer Emma Tham) specifically ordered for UMI workflow results and deeply looked into the generated UMI results. For the rest of the customers between BALSAMIC v7.5 to v9.0, we have generated the UMI results for all panels. But to my knowledge no one has looked into the metrics in detail, to bring some conclusions.

To my knowledge, one crucial metric could be the Median Target coverage value, both from total reads and after UMI collapsing. In order to detect very low AF sensitivities from UMI workflow (AF 0.05%), we need a good target coverage after UMI collapsing (~3000x), In relation to this, the sequencing depth also matters. Also, from Total sequenced reads, it is good to have the duplication rate. 

Related issue: https://github.com/Clinical-Genomics/cgp-cancer-umi/issues/2

Some of these metrics are generated and stored in each analysis case folder `analysis/qc/umi_qc/`
but as mentioned needs more investigation from different projects to define the criteria.

**Comment by ivadym** [comment]
Closing as there doesn't seem to be an immediate need for this to be implemented. 

@Clinical-Genomics/cancer-bioinfo
